### ISSUE TITLE
Chrome notifies of data breach after login

### ISSUE THREAD

**Issue by glennfrutiz** [CS361-F2020/Project#63]
After logging into the application Google chrome displays the following alert : A data breach on a site or app exposed your password. Chrome recommends your password now.

Steps to reproduce

Create an account. 
Logout. 
Login to bookswap.
Alert is displayed upon reaching http://flip1.engr.oregonstate.edu:{portnumber}/search

**Comment by mkoeplin** [comment]
This is due to a Chrome feature and I believe is only triggered for users if it senses you are using the same password or logins multiple places. I don't receive this error and there is an article stating this is due to a Chrome specific feature. I think we can close this issue now since it's not something that can be resolved within the application code.
