### ISSUE TITLE
Request a book email confirmation title is "undefined" 

### ISSUE THREAD

**Issue by jung8** [CS361-F2020/Project#65]
When a user requests a book from the search page the user receives an email with the title of the book that was requested. The title in the email shows up as undefined. 

Steps to reproduce:
1. login
2. on the search page request a book
3. check email and the title of the book requested shows as "undefined"

**Comment by mkoeplin** [comment]
Please provide a more specific example as I was able to request multiple books and don't see the title as undefined for any of them. I would guess that either the code you are running is not up to date or that this is due to the already documented error with special characters in the title causing issues with any calls from the client that pass the title to the server. If this is the case, we don't need a second issue on it.
<img width="700" alt="Screen Shot 2020-12-03 at 4 25 40 AM" src="https://user-images.githubusercontent.com/55862880/100997546-fd9b3e00-351f-11eb-922f-2cae65f9f624.png">
